# Generated by Django 5.2.8 on 2025-11-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="사용자 구분용 세션 식별자",
                        max_length=255,
                        verbose_name="세션 ID",
                    ),
                ),
                ("user_question", models.TextField(verbose_name="사용자 질문")),
                ("bot_answer", models.TextField(verbose_name="챗봇 응답")),
                (
                    "sources",
                    models.JSONField(
                        blank=True,
                        help_text="RAG 검색 결과(JSON)",
                        null=True,
                        verbose_name="참고 자료",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="사용자 장치 또는 기타 부가 정보",
                        null=True,
                        verbose_name="요청 메타데이터",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "채팅 내역",
                "verbose_name_plural": "채팅 내역",
                "ordering": ["-created_at"],
            },
        ),
    ]
