# Generated by Codex on 2025-12-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_notification_reservation_waitstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatcache",
            name="cache_key",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chatcache",
            name="intent",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="chatcache",
            name="cache_scope",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="chatcache",
            name="normalized_query",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chatcache",
            name="rag_index_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="chatcache",
            name="top_k",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatcache",
            name="prompt_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="chatcache",
            name="context_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="chatcache",
            name="sources_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="chatcache",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
