# Generated by Codex on 2025-12-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_chatcache_cache_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("user_id", models.CharField(blank=True, max_length=255)),
                ("tool_name", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "툴 감사로그",
                "verbose_name_plural": "툴 감사로그",
            },
        ),
    ]
