# Generated by Codex on 2025-12-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_tool_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatcache",
            name="sources",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
