# Generated by Django 5.2.9 on 2026-01-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_chatcache_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalReservation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "patient_identifier",
                    models.CharField(db_column="patient_identifier", max_length=100),
                ),
                ("patient_name", models.CharField(blank=True, max_length=100)),
                ("doctor_name", models.CharField(blank=True, max_length=100)),
                ("doctor_department", models.CharField(blank=True, max_length=100)),
                ("start_time", models.DateTimeField(db_column="start_time")),
                (
                    "end_time",
                    models.DateTimeField(blank=True, db_column="end_time", null=True),
                ),
                ("status", models.CharField(max_length=50)),
                ("memo", models.TextField(blank=True, db_column="memo", null=True)),
            ],
            options={
                "db_table": "patients_appointment",
                "managed": False,
            },
        ),
    ]
