# Generated by Django 5.2.8 on 2025-11-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_hash", models.CharField(max_length=64, unique=True)),
                ("query", models.TextField()),
                ("context", models.TextField(blank=True)),
                ("response", models.TextField()),
                ("hit_count", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chatbot_cache",
                "ordering": ["-created_at"],
            },
        ),
    ]
